version: "3.9"
services:

 # Laravel App
  phpfpm:
    container_name: ${APP_CONTAINER}
    build:
      args:
        user: romandunik
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ${PROJECT_NAME}-network
    
  # Nginx Service
  nginx:
    container_name: ${WEB_CONTAINER}
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - ${PROJECT_NAME}-network

  # Postgres Service
#  db:
#    container_name: ${DB_CONTAINER}
#    image: postgres:14
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DP_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#    ports:
#      - "5432:5432"
#    networks:
#      - ${PROJECT_NAME}-network
      
networks:
  cinemator-network:
    driver: bridge
