version: "3.9"
services:

 # Laravel App
  phpfpm:
    build:
      args:
        user: romandunik
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    
  # Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - laravel-network
  
  # Mysql Service
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
    networks:
      - laravel-network
      
networks:
  laravel-network:
    driver: bridge
