version: "3.9"
services:

 # Laravel App
  phpfpm:
    container_name: app
    build:
      args:
        user: romandunik
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    tty: true
#    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    
  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine
#    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - laravel-network

  # Postgres Service
  db:
    image: postgres:14
#    restart: unless-stopped
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=laravel
    ports:
      - "5432:5432"
    networks:
      - laravel-network
      
networks:
  laravel-network:
    driver: bridge
